UKHomeOffice/hocs-info-service

- src/main/java/uk/gov/digital/ho/hocs/info/dto/GetTeamResponse.java
- src/main/java/uk/gov/digital/ho/hocs/info/member/MemberResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/member/MemberService.java
- src/main/java/uk/gov/digital/ho/hocs/info/repositories/MemberRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/repositories/TeamRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/team/TeamResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/team/TeamService.java
- src/test/java/uk/gov/digital/ho/hocs/info/team/TeamResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/team/TeamServiceTest.java
> Add /team/:id and /member/:id/team endpoints

- src/main/java/uk/gov/digital/ho/hocs/info/entities/Team.java
- src/main/java/uk/gov/digital/ho/hocs/info/repositories/TeamRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/team/TeamResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/team/TeamService.java
- src/test/java/uk/gov/digital/ho/hocs/info/member/MemberResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/team/TeamResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/team/TeamServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/topic/TopicResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/unit/UnitResourceTest.java
tbh i have lost track of what i am doing
> Add endpoint to look up teams by topic

- src/main/java/uk/gov/digital/ho/hocs/info/casetype/CaseTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/casetype/CaseTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/correspondentType/CorrespondentTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/deadline/DeadlinesService.java
- src/main/java/uk/gov/digital/ho/hocs/info/documentClient/DocumentClient.java
- src/main/java/uk/gov/digital/ho/hocs/info/documentClient/dto/CreateManagedDocumentRequest.java
- src/main/java/uk/gov/digital/ho/hocs/info/dto/CaseTypeDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/dto/CorrespondentTypeDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/dto/CreateStandardLineDocumentDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/dto/GetDeadlinesResponse.java
- src/main/java/uk/gov/digital/ho/hocs/info/dto/GetMembersAddressResponse.java
- src/main/java/uk/gov/digital/ho/hocs/info/dto/UserDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/entities/CaseTypeEntity.java
- src/main/java/uk/gov/digital/ho/hocs/info/entities/CorrespondentType.java
- src/main/java/uk/gov/digital/ho/hocs/info/entities/HouseAddress.java
- src/main/java/uk/gov/digital/ho/hocs/info/entities/Minister.java
- src/main/java/uk/gov/digital/ho/hocs/info/house/ingest/IrishMember.java
- src/main/java/uk/gov/digital/ho/hocs/info/house/ingest/IrishMembers.java
- src/main/java/uk/gov/digital/ho/hocs/info/repositories/CaseTypeRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/repositories/CorrespondentTypeRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/security/AccessLevel.java
- src/main/java/uk/gov/digital/ho/hocs/info/security/KeycloakService.java
- src/main/java/uk/gov/digital/ho/hocs/info/user/UserResource.java
- src/test/java/uk/gov/digital/ho/hocs/info/user/UserResourceTest.java
> Add UserDto and cleanup imports

- src/main/java/uk/gov/digital/ho/hocs/info/application/LogEvent.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/exception/RestResponseEntityExceptionHandler.java
- src/main/resources/logback-spring.xml
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicIntegrationTests.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicTeamIntegrationTests.java
- src/test/resources/application.properties
> More logging

- src/main/java/uk/gov/digital/ho/hocs/info/api/StandardLineResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/StandardLineService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TemplateResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TemplateService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/GetStandardLineResponse.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/GetTemplateResponse.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/SchemaDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Schema.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/SchemaRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/StandardLineRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TemplateRepository.java
- src/main/resources/db/postgresql/V1_999__SCHEMA_CASETYPE_STAGETYPE.sql
- src/test/java/uk/gov/digital/ho/hocs/info/api/StandardLineResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/StandardLineServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TemplateResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TemplateServiceTest.java
add stagetype to schema information
> add two endpoints needed for casework cache improvements

- src/main/java/uk/gov/digital/ho/hocs/info/HocsInfoServiceApplication.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TopicResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TopicService.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/ParentTopicRepository.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/ParentTopicRepositoryTest.java
Additional endpoint to list all parent topics.  Required for the management UI
> HOCS-1096-all-parent-topics-endpoint

- src/main/java/uk/gov/digital/ho/hocs/info/application/RequestData.java
- src/test/java/uk/gov/digital/ho/hocs/info/RequestDataTest.java
Changed the casing to make this consistent with the other services
> Fix X-Auth-UserId header

- src/main/java/uk/gov/digital/ho/hocs/info/domain/exception/RestResponseEntityExceptionHandler.java
… to the log for unhandled exceptions
> HOCS-1117-remove-from-team-error added stacktrace

- src/main/java/uk/gov/digital/ho/hocs/info/api/CountryResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CountryService.java
- src/main/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerService.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Country.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/CountryRepository.java
- src/main/resources/application.properties
- src/main/resources/db/postgresql/V1_17__CREATE_TABLE_COUNTRY.sql
- src/test/java/uk/gov/digital/ho/hocs/info/api/CountryResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CountryServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/CountryRepositoryTest.java
- src/test/resources/application-test.properties
- src/test/resources/application.properties
Download list of ~200 countries from official Gov API. Creates new PSQL table. (Displaying in UI to follow.) Merge to WCS.
> Provide list of official countries.

- src/main/java/uk/gov/digital/ho/hocs/info/api/StandardLineService.java
- src/main/java/uk/gov/digital/ho/hocs/info/client/caseworkclient/CaseworkClient.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/StandardLineResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/StandardLineServiceTest.java
added call to the casework service to invalidate the cache for the updated topic
> HOCS-1204-flush-standard-line-cache 

- src/main/java/uk/gov/digital/ho/hocs/info/api/TopicResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TopicService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/GetAllTopicsResponse.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ParentTopicAndTopicDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/CaseType.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/StageTypeEntity.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepository.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/dto/GetAllTopicsResponseTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/dto/ParentTopicAndTopicDtoTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/ParentTopicRepositoryTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepositoryTest.java
Filtering only allocated topics as the case will error if selecting an unallocated topic
> HOCS-1217 filter only allocated child topics

- src/main/java/uk/gov/digital/ho/hocs/info/api/DataService.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/DataServiceTest.java
New list of cohorts. Changed in mock after dev complete, before QA done. Merge to WCS.
> HOCS-1296 : change list of cohorts to full English

- src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaService.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/FieldRepository.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/SchemaResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/SchemaServiceTest.java
Update summary tab. Merge to WCS.
> HOCS-1318 : update summary tab

- src/main/java/uk/gov/digital/ho/hocs/info/api/CountryService.java
> HOCS-1441 : add caching to country API

- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/StageTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/StageTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Deadline.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/DeadlinesServiceTest.java
Set different M-Ref deadline for whole Case lifetime, not per stage.
Stage deadline of "-2" defaults to Case deadline.
Merge to UKVI2.
> HOCS-1581 : required by date for M-Ref cases

- src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TopicTeamService.java
- src/main/java/uk/gov/digital/ho/hocs/info/client/auditClient/AuditClient.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/TeamLink.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/ParentTopicRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamLinkRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepository.java
- src/main/resources/db/postgresql/V1_29__ALTER_TEAM_LINK_TABLE.sql
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamLinkIntegrationTests.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamLinkServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/ParentTopicRepositoryTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepositoryTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepositoryTest.java
- src/test/resources/beforeTest.sql
Convert link value from UUID to String.
New endpoint to get Team based on text link type.
Merge to UKVI2.
> UKVI2 HOCS-1582 : correspondence cases are sent to correct workstack

- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ConfigurationDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Configuration.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/DocumentTag.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/DocumentTagRepository.java
- src/main/resources/db/postgresql/V1_34__CREATE_DOCUMENT_TAG.sql
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/ConfigurationResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/ConfigurationServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/dto/ConfigurationDtoTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/DocumentTagRepositoryTest.java
New endpoint to get data from new document tag table, for given case type.
> HOCS-1551 : make document tags case type specific

- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/LocalDateWrapper.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/LocalDateWrapperImpl.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Deadline.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/HolidayDateRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/utils/DateUtils.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/LocalDateWrapperImplTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/utils/DateUtilsTest.java
(priority points calculation should take weekends and bank holidays into account)
> HOCS-1593 - UKVI Triage Take a Case

- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/StageTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/StageTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/StageTypeEntity.java
- src/main/resources/db/postgresql/V1_40__ADD_COLUMN_TO_STAGE_TYPE.sql
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/DeadlinesServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/StageTypeResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/StageTypeServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/model/StageTypeEntityTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/ParentTopicRepositoryTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepositoryTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepositoryTest.java
Additional column on stage type to hold deadline warning integer.
New endpoints for calculating this value for case and stage levels.
> HOCS-1568 : highlight in red any case approaching OOSS

- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/StageTypeEntity.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/DeadlinesServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/StageTypeResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/StageTypeServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/model/StageTypeEntityTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/ParentTopicRepositoryTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepositoryTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepositoryTest.java
- src/test/resources/beforeTest.sql
Add support for DB "display_sort_order" and use it when streaming stage data to deadline dates.
> HOCS-1820 : sort stage deadlines by progression, fix

- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/SchemaDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Schema.java
- src/main/resources/db/postgresql/V1_43__ADD_PROPS_TO_SCREEN_SCHEMA.sql
- src/test/java/uk/gov/digital/ho/hocs/info/api/SchemaServiceTest.java
-added new 'props' property at screen_schema level, this will hold any frontend
specific config/enrichments e.g. validationSuppressors at screen level. It can be expanded to include
more screen level frontend customisation
> HOCS-1862 - Ability to suppress validation on certain actions

- src/main/java/uk/gov/digital/ho/hocs/info/domain/entity/Entity.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityService.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityTest.java
- added endpoint to get entity details by uuid
- added endpoint to update entity 'data' property (which contains title)
> HOCS-1875 - UKVI Campaign - Amend

- src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TopicTeamResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TopicTeamService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/TopicTeamDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/TopicTeam.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepository.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicTeamResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicTeamServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/dto/TopicTeamDtoTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepositoryTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepositoryTest.java
New endpoints for returning topics and teams.
> HOCS-1938 : export topics and teams

- .drone.yml
- src/main/resources/application.properties
Flyway has been disabled as planned, so data scripts can be run with flyway inside hocs-data repo.
> HOCS-1858: CI Database Improvements

- src/main/java/uk/gov/digital/ho/hocs/info/client/audit/client/AuditClient.java
The exchange pattern setting does not work.
Reverts UKHomeOffice/hocs-info-service#230
> Revert "Hocs 2095 audit fail error"

- src/main/java/uk/gov/digital/ho/hocs/info/client/audit/client/AuditClient.java
- src/main/java/uk/gov/digital/ho/hocs/info/client/audit/client/dto/CreateAuditRequest.java
As a result of receiving a prod audit exception, we are improving the logging around this area to pinpoint the issue.
> HOCS-2095: Improve logging around Audit

- src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepository.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java
Endpoint for all teams added (including inactive teams)
> HOCS-2267 Extract Active Teams

- src/main/java/uk/gov/digital/ho/hocs/info/security/KeycloakService.java
- src/test/java/uk/gov/digital/ho/hocs/info/security/KeycloakServiceTest.java
At present we don't have any pagination in the getUsersForTeam 
function. This is causing us to return the maximum of 100 users 
for an individual team, even if that team has more than 100.
> HOCS-2421: add pagination to getUsersForTeam

- src/main/java/uk/gov/digital/ho/hocs/info/api/UserResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/UserService.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/UserResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/UserServiceTest.java
New endpoint to return given user in given team.
> HOCS-2015 : When case converted then remove allocation if user not in new team

- src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Unit.java
- src/main/resources/db/postgresql/V1_45__2367-BulkTransferColumn.sql
- src/test/java/uk/gov/digital/ho/hocs/info/api/TeamResourceTest.java
* Add new endpoint for move team options
> hocs-2367-bulk-transfer-of–cases-from-one-team

- .drone.yml
Adding the build step for deployment to QAX.
> HOCS-2492 Create QAX Namespace

- src/main/java/uk/gov/digital/ho/hocs/info/api/NominatedContactService.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/NominatedContactServiceTest.java
This reverts commit 4f88d07a6c1994fcee661ef82910f58fd3935555.
> Revert "HOCS-2605 Cannot remove last nominated contact"

- src/main/java/uk/gov/digital/ho/hocs/info/application/SpringConfiguration.java
- src/main/java/uk/gov/digital/ho/hocs/info/application/SwaggerConfiguration.java
- src/main/resources/application.properties
This ticket updates the identifying label on the existing Swagger service on info service. 
The Swagger page is available at http://localhost:8085/swagger-ui.html
> HOCS-2457 add description label to Swagger service

- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeServiceTest.java
* Handle deadline extensions when calculating deadlines
> HOCS-2583 FOI User able to request PIT extension

- src/main/java/uk/gov/digital/ho/hocs/info/api/TopicResource.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/TopicResourceTest.java
Added a new service to the Topic Resource which retrieves a list of FOI specific topics.
> HOCS-3251 add foi topics service

- src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/FieldDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/SchemaDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Field.java
- src/main/resources/db/postgresql/V1_47__FIELD_AND_ALTER_SCREEN_SCHEMA.sql
- src/test/java/uk/gov/digital/ho/hocs/info/api/ExtractServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/SchemaIntegrationTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/SchemaResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/SchemaServiceTest.java
- src/test/resources/afterTest.sql
- src/test/resources/beforeTest.sql
* Allow fields to compose other fields
> HOCS-3287 Check your answers screen

- build.gradle
- src/main/java/uk/gov/digital/ho/hocs/info/api/CountryResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CountryService.java
- src/main/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerService.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Country.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Team.java
- src/main/java/uk/gov/digital/ho/hocs/info/startup/RefreshCountries.java
- src/main/resources/application.properties
- src/test/java/uk/gov/digital/ho/hocs/info/api/CountryResourceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/CountryServiceTest.java
- src/test/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerServicesTests.java
- src/test/resources/application-test.properties
- src/test/resources/application.properties
* HOCS-3031 - Fix country list refresh.
* HOCS-3031 - Update test properties
* HOCS-3031 - Fix lombok warnings
* HOCS-3031 - Refresh countries on startup
> Feature/hocs 3031 nationality list (#296)

- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/ConfigurationService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CountryService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/EntityResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/PriorityPolicyService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/ProfileResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/UserService.java
- src/main/java/uk/gov/digital/ho/hocs/info/application/SpringConfiguration.java
Remove Cache from the info service - cache should be on the caller only
> 🐛 Hocs-4388: Remove Cache from the info service

- .github/workflows/semver-data.yml
Specify the type of the input to be choice - this enforces a dropdown
menu.
> HOCS-4696: specify type of action input

- .drone.yml
This reverts commit 75b25d61ec5b9a675586ce350cf994e7f01a31a7.
This reverts commit 83e0124ffffb678a275b9df88f265fa933e79bc6.
> Revert Drone Downstream Changes

- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseDetailsFieldResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/CaseDetailsFieldService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaResource.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaService.java
- src/main/java/uk/gov/digital/ho/hocs/info/api/dto/CaseDetailsFieldDto.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/model/CaseDetailsField.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/CaseDetailsFieldRepository.java
- src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/SchemaRepository.java
Mark the methods around the accordion data retrieval as deprecated for removal as this has been refactored out the service.
> HOCS-5569: mark classes/methods for deprecation

- src/main/java/uk/gov/digital/ho/hocs/info/api/StageTypeResource.java
- src/test/java/uk/gov/digital/ho/hocs/info/api/StageTypeResourceTest.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6266
Used to fill in cache misses in https://github.com/UKHomeOffice/hocs-casework/pull/900 when new stages are added.
> [HOCS-6266] Add an endpoint to get a stage by type name
