UKHomeOffice/hocs-info-service

keycloak/local-realm.json
src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
src/main/java/uk/gov/digital/ho/hocs/info/application/CacheScheduler.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Permission.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/CaseTypeRepository.java
src/main/java/uk/gov/digital/ho/hocs/info/security/KeycloakService.java
src/main/java/uk/gov/digital/ho/hocs/info/security/UserPermissionsService.java
src/main/resources/application.properties
src/test/java/uk/gov/digital/ho/hocs/info/CacheSchedulerTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamIntegrationTests.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/security/KeycloakServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/security/UserPermissionsServiceTest.java

This changes the permissions model to only put the team UUID (case64 encoded) into Keycloak. The Permissions are now looked up on Info Service (cached locally).

New permissions

---

src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Schema.java

Fix: sort fields on schema by primary key id (to match insertion sequence).

Sort fields on schema by primary key id (to match insertion sequence).

---

src/main/resources/db/postgresql/V1_15__ADD_CONSTRAINT_TO_FIELD_SCREEN.sql

Add unique constraint to field_screen table to prevent duplicates, e.g. when repeatedly running the insertion scripts.

Add unique constraint to field_screen table.

---

src/main/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerService.java

We do not notice the crash as MEP's were the last group to be fetched anyway.

null MEP were causing the member refresh to crash.

---

src/main/java/uk/gov/digital/ho/hocs/info/api/UserService.java
src/main/java/uk/gov/digital/ho/hocs/info/client/caseworkclient/CaseworkClient.java
src/test/java/uk/gov/digital/ho/hocs/info/api/UserServiceTest.java

Use stage_type.acting_team_uuid to get team UUID instead of stage_data.team_uuid. This is because stage_data.team_uuid is often empty, whereas stage_type.acting_team_uuid is not.

HOCS-1836: fix for issue when loading completed DCU cases.

---

src/main/resources/db/postgresql/V1_42__ALTER_TABLE_STAGE_TYPE.sql

Null values in stage_type.display_stage_order column are making the service error.

HOCS-1848 : prevent stage_type.display_stage_order column null values

---

src/main/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityRepository.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityResource.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityService.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/entity/dto/EntityDto.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/entity/EntityServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/entity/dto/EntityDtoTest.java

- excluded 'MPAM_CAMPAIGNS' entity list from cache
- added ability to add new items to entity lists (new endpoint and
service implementation)
- EntityDto now also includes UUID, it will be required for editing.

HOCS-1758 - UKVI Campaign - Add New

---

src/main/java/uk/gov/digital/ho/hocs/info/api/StandardLineResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/StandardLineService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/UpdateStandardLineDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/StandardLine.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/StandardLineRepository.java
src/test/java/uk/gov/digital/ho/hocs/info/api/StandardLineResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/StandardLineServiceTest.java

-added endpoint for fetching single standard line info
-added endpoint for fetching all standard lines
-renamed incorrectly named method (createDocument)
-added endpoint to update standard line (covers expiryDate and
displayName)
-added endpoint to expire standard line
-added endpoint to delete standard line
-added workaround to fix localdatetime bug (end of day - 1 hour) -
this needs more looking into as the solution is less than perfect.

HOCS-1855 - Standard Lines - Management

---

src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/TopicTeamResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/TopicTeamService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/data/SimpleMapItem.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepository.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TopicTeamResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TopicTeamServiceTest.java

-added endpoint for fetching simple mapping representing topic uuid to
team (display name) responsible for passed in stage
- removes some redundant call in test file to 'times(1)' and
'doNothing()'
The logic uses team_link table in the background to find all mappings
for chosen stage where link_type == 'TOPIC'.
Spring data projection has been used to map sql output to SimpleMapItem.
This is so that this generic interface could be reused in the future.
For more details about spring data projection see:
https://www.baeldung.com/spring-data-jpa-projections

HOCS-2008 - Standard Lines Management - Improvements

---

build.gradle

As a result of a continuing error when removing a user from a team, the error revolves around Apache Camel. To rule out a potential version mismatch, this commit brings it inline with other projects (2.23.0).

HOCS-2095: Downgrade Apache Camel Version

---

src/main/java/uk/gov/digital/ho/hocs/info/client/audit/client/AuditClient.java
src/main/java/uk/gov/digital/ho/hocs/info/client/audit/client/dto/CreateAuditRequest.java

As a result of fixing the cause of audit log not working being isolated the reason. This logging is no longer required as the audit feature is working as intended now.

HOCS-2095: revert additional logging around Audit

---

.drone.yml

Before this commit, Drone deployments would deploy to cs-dev, and afterwards then deploy  to wcs-dev. This change makes it so the deployments to cs-dev and wcs-dev are done in parallel.

HOCS-2171: parallelise dev deployments

---

src/main/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerService.java

Add more detailed logging for investigation into members/refresh service failing on prod like environments.

HOCS-2124 : add logging for failed members list retrieval

---

src/main/java/uk/gov/digital/ho/hocs/info/api/StandardLineResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/StandardLineService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/TopicService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ConfigurationDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Configuration.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/StandardLineRepository.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepository.java
src/test/java/uk/gov/digital/ho/hocs/info/api/ConfigurationResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/ConfigurationServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/StandardLineResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/StandardLineServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TopicServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/dto/ConfigurationDtoTest.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/StandardLineRepositoryTest.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TopicRepositoryTest.java

This pull request adds the following functionality: 
- Pulls back the configuration from the database for viewing the standard lines button in the header. 
- Added functionality to be able to get all of the teams that are associated with a user at that time.
- Added the ability to get all of the active standard lines linked to a topic that is associated with a team. This will populate the new frontend screen to show the user all of the standard lines so that they can be downloaded.
Tests have been added for all of the features above. Tests have also been added to cover all of the standard lines endpoints.

HOCS-1853: add standard lines endpoints 

---

src/main/java/uk/gov/digital/ho/hocs/info/api/SomuTypeResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/SomuTypeService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/CreateSomuTypeDto.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/SomuTypeDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/SomuType.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/SomuTypeRepository.java
src/main/resources/db/postgresql/V1_77__2195_Multiple_Contributions_Add_Somu.sql
src/test/java/uk/gov/digital/ho/hocs/info/api/SomuTypeResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/SomuTypeServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/dto/SomuTypeDtoTest.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/model/SomuTypeTest.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/SomuTypeRepositoryTest.java

Endpoints added to Info for new Somu Types:
1. Get all.
2. Get by Case Type and Type.
3. Post to Upsert a Somu Type.
Includes SQL script to add Somu Type table, for use by unit tests during build.
Stopped thinking of "active=false" as being deleted.

HOCS-2214 : Multi.Contrib. endpoints for returning Somu Types

---

.drone.yml

Previously we were restarting the top job of hocs-data, which caused
problems. This changes that to fire a `cs-qa` deployment to hocs-data.
The name of this deployment is arbitrary and not currently used by the
downstream pipeline, which only cares about it being *a* deployment and
doesn't differentiate between them.
This commit also shortens the name of the associated build steps, as
they were getting truncated in the Drone CI user interface.

HOCS-2229 Use deployment when triggering databuild

---

src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java

This bug fix removes the @PostMapping annotation from the createCaseType method in CaseTypeResource. It has no parameters and did not function as an endpoint. It does not appear to be called. The method shall remain only the annotation is to be removed.
The side effect of no params means the annotation is applied to the base url and other http verbs appear to be blocked causing problems with swagger-ui.

HOCS-2260: remove incomplete mapping annotation

---

src/main/java/uk/gov/digital/ho/hocs/info/api/TopicResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/TopicService.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TopicIntegrationTests.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TopicServiceTest.java

This PR along with https://github.com/UKHomeOffice/hocs-management-ui/pull/65 addresses HOCS-2115 - Home Office sponsorship in CPFG.
The issue was caused by old deactivated subtopics being shown alongside and indistinguishable from new subtopics with same name appearing in the management console. This means that there's a 50/50 chance that the user will link the wrong subtopic to a team.
Changes in this PR:
* Add endpoint to show all active topics (filtering out deactivated topics) at /topics/active
* Reactivate child topics when an attempt is made to create a subtopic matching a deactivated subtopic for a given parent
* Update tests

HOCS-2115 - Home Office sponsorship in CPFG

---

src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/TopicDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Team.java

This PR along with https://github.com/UKHomeOffice/hocs-audit/pull/75 addresses HOCS-2262-Add active/inactive column to Topics extract
Changes in this PR:
* Add active boolean field to topic endpoints json

HOCS-2262-Add active/inactive column to Topics extract

---

src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeSchemaResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeSchemaService.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/CaseTypeSchema.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/CaseTypeSchemaRepository.java
src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeSchemaResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeSchemaServiceTest.java

At present we have no endpoint that returns a distinct list 
of the stages that are associated with a case type. 
This change adds a endpoint that queries the case_type_schema 
table for distinct stage types and returns them as a list.

HOCS-2419: add case type schema endpoint

---

src/main/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerService.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/enums/House.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/enums/HouseCodes.java
src/test/java/uk/gov/digital/ho/hocs/info/client/ingest/ListConsumerServicesTests.java

Currently if a house address does not exist within the database for specific API then when we come to populating the members we get a Null Pointer Exception. This is causing specific live systems fail with this during a CronJob to refresh the members list. As the CronJob is set to restart 3 times this is triggering our SysDig alerts.
This change improves the general checking and makes it so that it fails graciously if a HouseAddress does not exist in the system. We now get a log output if the HouseAddress does not exist but it continues to try for the rest.

HOCS-2213: fixup House Address on List Consumer API calls

---

src/main/java/uk/gov/digital/ho/hocs/info/api/UserResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/UserService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/CreateUserResponse.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/UpdateUserDto.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/UserDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/exception/RestResponseEntityExceptionHandler.java
src/main/java/uk/gov/digital/ho/hocs/info/security/KeycloakException.java
src/main/java/uk/gov/digital/ho/hocs/info/security/KeycloakService.java
src/main/java/uk/gov/digital/ho/hocs/info/utils/EmailDomainValidator.java
src/main/java/uk/gov/digital/ho/hocs/info/utils/EmailDomainWhitelisted.java
src/main/resources/application.properties
src/test/java/uk/gov/digital/ho/hocs/info/api/UserIntegrationTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/UserResourceRestTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/UserResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/UserServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/dto/CreateUserDtoTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/dto/UpdateUserDtoTest.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/exception/RestResponseEntityExceptionHandlerTest.java
src/test/java/uk/gov/digital/ho/hocs/info/security/KeycloakServiceTest.java
src/test/resources/application.properties

This is to support adding users in the Management UI.
There are new new UserResource endpoints for adding and updating users, with associated changes in the services.
Exception handling has been modified, while still supporting existing behaviour. The changes were required to support meaningful validation messages in the Management UI.
1. MethodArgumentNotValidException returns the specific reason the validation failed.
2. KeyCloakException now has a statusCode property which can store the status code received from the Keycloak server. This can then be used in the response to the client.

HOCS-2452 Supporting Add User in ManagementUI

---

src/main/resources/application.properties
src/test/java/uk/gov/digital/ho/hocs/info/api/UserResourceRestTest.java
src/test/resources/application.properties

As we currently store the whitelisted domains in 
the `application.properties` file. We need to add 
an extra record so that the `@hmpo.gov.uk` email 
address is whitelisted and thus new user accounts 
can be created with it.

HOCS-2616: add hmpo to whitelist domain

---

src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepository.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java

If a team already exists during team creation on the createTeam method, an exception be thrown. This also means a 409 response will be sent from the team creation resource which uses the createTeam method.

HOCS-2502: Throw exception if team already exists.

---

.drone.yml

Currently we are using the old implementation of the 
`hocs-version-bot`. As this has been changed and improved, the 
use case has been altered.

HOCS-2642: fix version bot

---

.drone.yml

Currently we are incorrectly using the downstream drone plugin. As
per the documentation (http://plugins.drone.io/drone-plugins/drone-downstream/)
the parameters should be wrapped in the settings object.

HOCS-2642: fix usage of downstream plugin

---

.drone.yml

Currently when we push to a data repo it restarts both `cs-dev` and 
`wcs-dev`. This is suboptimal as we should only be restarting the 
environment it applies too. This change allows for singular restarts
and to allow for both environment restarts too.

HOCS-2642: improve restart trigger

---

.drone.yml

In the deployment pipeline we let through any promotions, as when 
we restart we aren't triggering an actual `promote` but more a 
restart this means we should exclude this from the deployment 
pipeline.

HOCS-2642: exclude target

---

.drone.yml

Currently we have issues with caching issues on drone when doing 
restarts. To fix this we have introduced a restart shell file to handle 
the restarting of the services. As a result multiple of the environment
variables can be removed.

HOCS-2642: change to use restart file

---

src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepository.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/repository/TeamRepositoryTest.java

Presently, the updateTeamName service method does the rename 
blindly. This change does the following: checks if a rename conflict is 
present, evicts the cache of the teams to allow for the update.

HOCS-2743: improve the updateTeamName method

---

src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
src/main/java/uk/gov/digital/ho/hocs/info/application/aws/LocalStackConfiguration.java
src/main/java/uk/gov/digital/ho/hocs/info/application/aws/SqsConfiguration.java
src/main/java/uk/gov/digital/ho/hocs/info/client/notifyclient/NotifyClient.java
src/main/java/uk/gov/digital/ho/hocs/info/client/notifyclient/dto/EventType.java
src/main/java/uk/gov/digital/ho/hocs/info/client/notifyclient/dto/TeamRenameCommand.java
src/main/resources/application-local.properties
src/main/resources/application-sqs.properties
src/main/resources/application.properties
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/client/notifiyclient/NotifyClientTest.java
src/test/resources/application.properties

When a user renames a team through MUI, we should send a notification to the teams nominated contacts. To allow for this this change adds a NotifyClient that puts a command onto the hocs-notify queue. This NotifyClient is called after the rename has taken place in the `updateTeamName` method in the `TeamService`. To allow for the command to be put onto the queue this change also handles all of the required application properties.

HOCS-2788: send rename notification to notify queue

---

src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
src/main/java/uk/gov/digital/ho/hocs/info/application/CacheScheduler.java
src/test/java/uk/gov/digital/ho/hocs/info/CacheSchedulerTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamResourceTest.java

At present we have individual service caches, which can become out 
of date easily as we run multiple service pods. This causes potential 
inaccuracies of data between pods. This side effect means the user 
does not always see up to to date teams now we support adding 
them dynamically through MUI.

HOCS-2674: remove team caching

---

.drone.yml

This adds a step to Drone that fires on push to the FOI epic branch,
which triggers a deployment to the hocs-gamma environment.
Previously we were deploying manually to hocs-gamma, and using a fixed
branch-based tag, which was causing inconsistencies and confusion. Here
we deploy a tag based on the Drone build number, which is easier to
track. If we wanted, we could deploy using the SHA hash for a similar
effect.

HOCS-2885 Automatically deploy to gamma on push

---

src/main/java/uk/gov/digital/ho/hocs/info/api/dto/PatchTeamDto.java

The change unit functionality is broken due to a case mismatch - 'UUID' is used throughout the MUI, but 'Uuid' is the more common variant in hocs-info-service. Standardising this would be a long task spanning all of the repos, so this fix updates the PatchTeamDto to accept the variant used in the MUI.

HOCS-2583 Move a team to a different unit via MUI - fix

---

src/main/java/uk/gov/digital/ho/hocs/info/api/StageTypeResource.java
src/test/java/uk/gov/digital/ho/hocs/info/api/StageTypeResourceTest.java

Update case notes to display clearly whether they refer to a case allocation or a case rejection.
Allocation notes should show:
The team which made the allocation
The team the case was allocated to
The stage at which the allocation took place
Rejection notes should show:
The team who rejected the case
The stage at which the rejection took place

HOCS-3064: improve allocation notes by adding additional information

---

src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamResourceTest.java

added an endpoint on info service which returns a base64 code (for use in ModHeader) for a given team UUID.

HOCS3243 add dev tool to resolve team code

---

src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Deadline.java
src/main/java/uk/gov/digital/ho/hocs/info/utils/DateUtils.java
src/test/java/uk/gov/digital/ho/hocs/info/domain/model/DeadlineTest.java
src/test/java/uk/gov/digital/ho/hocs/info/utils/DateUtilsTest.java

Currently cases that have been received on a non-working day have that date be the start of the counter. It should be that the next working day starts the counter. As a result this change moves the received date forward to the next working day ready for the countdown to begin.
To support this change a simplification of the DateUtil class has been added.

HOCS-3631: case deadline dates

---

src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/ProfileResource.java
src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/ProfileResourceTest.java

- Additional parameter on `/caseType` to allow option of returning cases with a previous type. Defaulted this to false to avoid breaking any existing calls to the endpoint.
- Modified the `/profileNames` endpoint to return all case types for user, including cases with a previous type.

HOCS-3720: Add Complaints Stage 2 to search

---

src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java

Ensures by default getAllCaseTypes method returns all case types unless explicitly told otherwise.

HOCS-3901 Fix extracts for case types with previous case types

---

src/main/java/uk/gov/digital/ho/hocs/info/domain/model/WorkstackColumn.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/WorkstackType.java
src/test/java/uk/gov/digital/ho/hocs/info/api/ConfigurationResourceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/ConfigurationServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/dto/ConfigurationDtoTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/dto/WorkstackColumnDtoTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/dto/WorkstackTypeDtoTest.java

WorkstackColumn and WorkstackType now link to the new uuid column that
has been reworked into the WorkstackColumn to replace the id primary key.
This has led to a few tests needing to be reworked for this new uuid
column.

HOCS-2399: rework tests to use the new uuid column

---

src/main/java/uk/gov/digital/ho/hocs/info/api/EntityService.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/EntityRepository.java
src/test/java/uk/gov/digital/ho/hocs/info/api/EntityServiceTest.java

Currently, there is no check for duplicate titles when amending an
entity. This change adds a check and throws an
EnityAlreadyExistsException if a duplicate title is found.

HOCS-3836: Add duplicate check for amending entity

---

build.gradle
src/main/java/uk/gov/digital/ho/hocs/info/HocsInfoServiceApplication.java
src/main/java/uk/gov/digital/ho/hocs/info/application/RestHelper.java
src/main/java/uk/gov/digital/ho/hocs/info/client/notifyclient/NotifyClient.java
src/main/java/uk/gov/digital/ho/hocs/info/security/KeycloakService.java
src/main/resources/application-local.properties
src/main/resources/application.properties
src/test/resources/application.properties

As part of the investigation it was determined that the application was failing to create new threads for the retry code, we have given the pods more memory, but we don't believe we need to use @Retry or @async at all - we prefer to fail fast.

HOCS-4312 - remove retry and async annotations

---

build.gradle
docker-compose.yml

Current production Keycloak version is 11.0.2, this change upgrades the
outdated dependency to this version. This change also pegs the version
of Keycloak used in the internal `docker-compose` file to use 11.0.2.

HOCS-4532: upgrade keycloak library to 11.0.2 

---

.github/dependabot.yml

As our Keycloak version has to be in line with the version that is in
the production environment provided by ACP. This change marks the
keycloak libraries as one to ignore as we will upgrade it inline with
ACP.

Dependabot: ignore keycloak dependency updates

---

kube/restart.sh

Upon moving the kube folder into the main repository the restart script
was missed. This has meant that all data only repo changes have not been
triggering this downstream restart pipeline. This change ports over the
restart script from the kube repository.

Pipeline: add missing restart script

---

kube/kd/deployment.yaml

The domain for the cfssl-sidekick-jks is currently pointing as
hocs-casework. This change points the domain to the correct kubernetes
service.

HOCS-4261: fix cfssl-jks domain

---

.drone.yml

Add the correct dependency name to Sonar as the deploy on tag step is currently failing.

Hocs 4696: add the correct dependency name to Sonar

---

kube/.drone.yml

Add a Drone pipeline to the kube folder that changes to this folder are
validated before they get merged into main.
As our Drone instance supports the drone-tree-plugin, having this
within this folder ensure it only gets run on a change to this folder.

HOCS-4749: add linting/dry-run drone pipeline

---

.drone.yml
.github/workflows/semver-data.yml

When a data PR is closed, this sends a trigger to the `semver-data`
action that allows a tag based on that PRs labels to the info. This then
supports a fresh deploy and drone trigger to dev environments.

HOCS-4696: support tag on data

---

src/main/java/uk/gov/digital/ho/hocs/info/api/ConfigurationService.java

Stop logging the configuration. It adds logspam and is of little
practical use.

HOCS-4783 Remove redundant log line

---

.drone.yml

Instead of running the last successful build - we should choose to fork
the build instead.

Change data tag trigger options

---

.drone.yml

Remove the deploy option from the downstream plugin steps. Merge the CS
and WCS downstream build steps.

Change downstream build step

---

.drone.yml

For tagged builds we ensure that info service successfully builds its
tag before triggering data. This also allows a edge case whereby the
last build of data fails finishes after the downstream build.

Change drone ordering

---

.github/workflows/codeql-analysis.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

This change updates the version of Java that is developed against to be Java 17. 
Additionally - too support this, gradle has been updated to version `7.4.2`.

HOCS-5002:  use Java 17

---

.github/workflows/semver-data.yml

If a tag is not found for the SHA passed into the SemVer tag (if
skip-release moves the head pointer for example) default to use the head
of the branch.

Use latest main if tag for SHA not present

---

.github/workflows/semver-data.yml
.github/workflows/semver.yml

When a GitHub job fails there is currently know way of identifying this,
this change sends a notification to a channel of our choosing to flag
that there is an issue that needs looking at.

Add GitHub Action Slack failure notification

---

src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Field.java
src/main/resources/db/postgresql/V1_55__4478_SwapIdForUuid.sql
src/test/resources/beforeTest.sql

Repoint the child field from the `child_field_id` to `child_field`.

HOCS-4478: repoint to new column

---

build.gradle
docker-compose.yml
keycloak/local-realm.json
src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/UserResource.java
src/main/java/uk/gov/digital/ho/hocs/info/security/KeycloakService.java
src/test/java/uk/gov/digital/ho/hocs/info/api/CaseActionIntegrationTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/CaseTypeIntegrationTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamIntegrationTests.java
src/test/java/uk/gov/digital/ho/hocs/info/api/TeamServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/UserIntegrationTest.java
src/test/java/uk/gov/digital/ho/hocs/info/api/UserServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/security/keycloak/KeycloakServiceIntegrationTest.java
src/test/java/uk/gov/digital/ho/hocs/info/security/keycloak/KeycloakServiceTest.java
src/test/java/uk/gov/digital/ho/hocs/info/utils/BaseKeycloakTest.java
src/test/resources/afterTest.sql
src/test/resources/application-integration.properties
src/test/resources/application-integration.yaml
src/test/resources/beforeTest.sql
src/test/resources/local-realm-integration.json

Upgrade the Keycloak instance to the latest production value to enable
maximum compatibility. This also updates the docker-compose to start up
the same version.
Paginating 100 users at a time is causing quite the overhead in Keycloak
due to the use of Redis caching implementation. This change passes
through `-1` for the size to return all. This removes multiple calls to
keycloak to zip them together.

Update Keycloak and Usages

---

kube/kd/deployment.yaml

The NI Assembly data service info-service looks up is only available via
plain old HTTP (:80) and 404s if you try HTTPS (:443). Prior to this
commit hocs-info-service was configured to route outbound HTTPS requests
through the outbound proxy, but not HTTP requests, meaning that the NI
Assembly request times out.
This commit tells hocs-info-service explicitly to go via the outbound
proxy for HTTP requests as well.
This commit also fixes a typo in the config: the non-proxy host list
only applied to HTTP but was probably meant to apply only to HTTPS.

HOCS-5057 Fix MLA lookup

---

kube/kd/deployment.yaml

When the HTTPS non-proxy host is set and HTTP non-proxy host is unset,
the info-service casework call for DCU primary topic fails because it
gets routed incorrectly via the outbound proxy.
I don't understand why that's the case, or why it would only affect
primary topics, but this commit reverts the change I made, as HTTP
non-proxy hosts are clearly more loadbearing than I had assumed.

HOCS-5284 Revert non-proxy hosts config change

---

.drone.yml

To ensure that multiple tags aren't released at the same time we use a
concurrency limit of 1 within the drone `build tag` step. While this
works it blocks over release candidates (after quick merge) from
starting until the previous job is complete. While this isn't
necessarily wrong there is no reason why a tag cannot be build and its
necessary data builds also built. This change moves the concurrency to
the deploy step to speed up things when multiple changes have been
merged in a short amount of time.

Move drone concurrency limit

---

.github/workflows/semver-data.yml

When we make a change in hocs-data or wcs-data we CURL back to hocs-info service to trigger a new build, I'm not a fan of this behaviour but we should not regress the behaviour for now.
This was caused by a restriction in github actions, where an event raised by a GH action (Tag) can't trigger another GU action (docker-build-on-tag), so we must temporarily duplicate the docker build behaviour.

HOCS-5271: reintroduce hocs-data tag hack

---

kube/kd/refreshmembers.yaml

This container is still a java container, but it is the base (actually parent) image for our services, so should already be present in the cluster level registry and will be maintained by us. Either way it's only 45Mb vs 400Mb

HOCS-2141: Use a smaller container for cron job.

---

src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/FieldDto.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/SchemaDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Schema.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/FieldRepository.java
src/main/resources/db/postgresql/V1_57__5363_AddSummaryToScreenSchema.sql
src/test/java/uk/gov/digital/ho/hocs/info/api/SchemaServiceTest.java

To support screens that can have a summary after the submit button this
change allows for the return of the `screen_schema.summary` column from
the database. As this is a JSONB value, we flag that this should return
the JSON raw value.

HOCS-5363: support summary screen column

---

src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/CaseTypeService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/CaseConfigDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/CaseConfig.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/CaseTabRepository.java

As case tabs are now served from a frontend configuration file, this
change marks all related functionality as deprecated pending future
removal.

HOCS-5363: mark case config as deprecated

---

src/main/java/uk/gov/digital/ho/hocs/info/api/ExtractService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaService.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/SchemaRepository.java

Deprecate all methods related to reporting as it is no longer used due
to a refactor.

HOCS-5279: deprecate reporting methods

---

src/main/java/uk/gov/digital/ho/hocs/info/api/ExportViewResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/ExportViewService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ExportViewDto.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ExportViewFieldAdapterDto.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/ExportViewFieldDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/ExportView.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/ExportViewRepository.java

Deprecate all methods related to custom export views as is longer
required due to a refactor.

HOCS-5279: deprecate custom export view methods

---

kube/deploy.sh

Add `gro.gov.uk` to the accepted email domains that users can be created
with.

HOCS-5489: add gro email domain

---

src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaResource.java
src/main/java/uk/gov/digital/ho/hocs/info/api/SchemaService.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/FieldDto.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/SchemaDto.java
src/main/java/uk/gov/digital/ho/hocs/info/api/dto/SecondaryActionDto.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/FieldScreen.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/Schema.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/model/SecondaryAction.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/FieldRepository.java
src/main/java/uk/gov/digital/ho/hocs/info/domain/repository/SchemaRepository.java

Mark all classes linked to Screens, Fields and SecondaryActions as deprecated as no longer required due to refactoring.

HOCS-5281: deprecate non-required classes

---

build.gradle

Add a comment in the gradle configuration to keep the version in lockstep with version in the data Dockerfiles.

Add comment to build.gradle around Flyway version

---

.github/workflows/manual-build-push.yml

The workflow is not valid. .github/workflows/manual-build-push.yml (Line: 17, Col: 9): Unexpected value 'ref'

Fix Invalid workflow file: .github/workflows/manual-build-push.yml#L17
